# Generated by Django 4.0.3 on 2022-06-07 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={},
        ),
        migrations.RemoveField(
            model_name='chat',
            name='timestamp',
        ),
    ]
