# Generated by Django 4.0.3 on 2022-04-03 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_usercourses_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourses',
            name='course',
        ),
        migrations.AddField(
            model_name='usercourses',
            name='course',
            field=models.ManyToManyField(to='courses.course'),
        ),
        migrations.AlterField(
            model_name='usercourses',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
