# Generated by Django 4.0.3 on 2022-06-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='q1option3',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='q1option4',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='q2option3',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='q2option4',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='q3option3',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='q3option4',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='q4option3',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='q4option4',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='q5option3',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='q5option4',
        ),
    ]
